// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9n6Ha6aJTF7pOeZMLfiSTi1pE0yMU7Es',
    appId: '1:352236395781:web:1f191279ffcb0c2c18eb6c',
    messagingSenderId: '352236395781',
    projectId: 'onecharge-26995',
    authDomain: 'onecharge-26995.firebaseapp.com',
    storageBucket: 'onecharge-26995.firebasestorage.app',
    measurementId: 'G-LNY2VB9DZZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBz0-l-39qUUKU9NP52Y33jR6So40hmtJk',
    appId: '1:352236395781:android:d44c436f0fc4d43218eb6c',
    messagingSenderId: '352236395781',
    projectId: 'onecharge-26995',
    storageBucket: 'onecharge-26995.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiDLi638MAKWw9-WOO7VlU2EXPsIBp_tc',
    appId: '1:352236395781:ios:8e5866e9d0e11bb118eb6c',
    messagingSenderId: '352236395781',
    projectId: 'onecharge-26995',
    storageBucket: 'onecharge-26995.firebasestorage.app',
    iosBundleId: 'com.onecharge.io',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiDLi638MAKWw9-WOO7VlU2EXPsIBp_tc',
    appId: '1:352236395781:ios:a14b600b6638f3dc18eb6c',
    messagingSenderId: '352236395781',
    projectId: 'onecharge-26995',
    storageBucket: 'onecharge-26995.firebasestorage.app',
    iosBundleId: 'com.example.onecharge',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9n6Ha6aJTF7pOeZMLfiSTi1pE0yMU7Es',
    appId: '1:352236395781:web:248238f1888d9df018eb6c',
    messagingSenderId: '352236395781',
    projectId: 'onecharge-26995',
    authDomain: 'onecharge-26995.firebaseapp.com',
    storageBucket: 'onecharge-26995.firebasestorage.app',
    measurementId: 'G-SBN47G3PTR',
  );
}
